# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likes', '0001_initial'),
        ('users', '0002_user_description'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_post',
            name='postLiked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likePost', to='message.Post'),
        ),
        migrations.AddField(
            model_name='like_post',
            name='userWhoLiked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_PostUser', to='users.User'),
        ),
        migrations.AddField(
            model_name='like_comment',
            name='commentLiked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeComment', to='message.Comment'),
        ),
        migrations.AddField(
            model_name='like_comment',
            name='userWhoLiked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_ReplyUser', to='users.User'),
        ),
    ]
