# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-05 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181105_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='profile',
        ),
    ]
