# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='defaultProfile.jpg', upload_to='image/'),
        ),
    ]
